_wandb:
    value:
        cli_version: 0.22.0
        e:
            rdvubrgtwi1ugc0o7fwpsdmbv3vtglid:
                args:
                    - --config_args_path
                    - configs/mnist.yml
                codePath: train_mnsit.py
                codePathLocal: train_mnsit.py
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "534724198400"
                        used: "257605914624"
                email: omezzinew@gmail.com
                executable: /home/wessim/miniconda3/envs/mfcvae/bin/python
                host: Wessim
                memory:
                    total: "33066475520"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.17
                program: train_mnsit.py
                python: CPython 3.8.20
                root: /home/wessim/PHD/Clustering(SophIA)/MFCVAE
                startedAt: "2025-10-28T15:43:59.997184Z"
                writerId: rdvubrgtwi1ugc0o7fwpsdmbv3vtglid
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 51
                - 53
            "2":
                - 1
                - 5
                - 41
                - 51
                - 53
            "3":
                - 1
                - 61
            "4": 3.8.20
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
J_n_mixtures:
    value: 2
activation:
    value: relu
batch_size:
    value: 512
config_args_path:
    value: ""
cov_type_p_z_c:
    value: diag
data_init:
    value: false
dataset:
    value: mnist_13rot
dataset_on_gpu:
    value: true
dec_backbone_dims:
    value:
        - 500
        - 500
dec_backbone_n_hidden:
    value:
        - 1
        - 1
dec_rung_dims:
    value:
        - 500
        - 2000
dec_rung_n_hidden:
    value:
        - 1
        - 1
decode_layer_dims:
    value:
        - - 500
          - merge
          - 500
        - - 2000
          - 500
device:
    value: cpu
do_fc_batch_norm:
    value: false
do_progressive_training:
    value: true
do_test_during_training:
    value: true
do_vis_cluster_means:
    value: true
do_vis_conf_mat:
    value: true
do_vis_examples_per_cluster:
    value: true
do_vis_latent_code_traversal:
    value: true
do_vis_n_samples_per_cluster:
    value: true
do_vis_pi:
    value: true
do_vis_recon:
    value: true
do_vis_sample_generations_per_cluster:
    value: true
do_vis_test:
    value: true
do_vis_train:
    value: true
enc_backbone_dims:
    value:
        - 500
        - 2000
enc_backbone_n_hidden:
    value:
        - 1
        - 1
enc_rung_dims:
    value:
        - -1
        - -1
enc_rung_n_hidden:
    value:
        - -1
        - -1
encode_layer_dims:
    value:
        - - 500
          - branch
        - - 2000
          - branch
eval_batch_size:
    value: 512
facet_to_fix_pi_p_c:
    value: all
fix_pi_p_c:
    value: false
fixed_var_init:
    value: 0.01
gamma_kl_c_pretrain:
    value: 0
gamma_kl_z_pretrain:
    value: 0
init_lr:
    value: 0.0005
init_off_diag_cov_p_z_c:
    value: false
init_type_p_z_c:
    value: gmm
lr_decay:
    value: 1
min_lr:
    value: null
model_type:
    value: fc_vlae
n_batches_fade_in:
    value: 15000
n_clusters_j_list:
    value:
        - 2
        - 2
n_epochs:
    value: 201
n_epochs_per_progressive_step:
    value:
        - 201
        - 201
n_examples_per_cluster:
    value: 16
n_recons_per_cluster:
    value: 4
n_sample_generation_plots_per_facet:
    value: 3
n_sample_generations_per_cluster:
    value: 8
n_test_batches:
    value: -1
save_model:
    value: true
seed:
    value: 3
sigma_multiplier_p_x_z:
    value: 0.35
temp_sample_generation:
    value: 1
user:
    value: user1
vis_every_n_epochs:
    value: 25
wandb_mode:
    value: online
z_j_dim_list:
    value:
        - 5
        - 5
